### ISSUE TITLE
💎 Select gems and build commented Gemfile

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/contacts-portal#1]
A Gemfile lists all dependencies. Ensure that the project has a good selection of the most useful gems for RoR projects.

Last course's Gemfile is a good starting point: https://github.com/hpi-swt2/lecture-portal/blob/dev/Gemfile

- [x] Make sure all gems are up-to-date
- [x] Make sure all gems are commented, including their benefit and links to websites
- [x] Ensure gems work with the selected Rails and Ruby version and throw no runtime errors in production mode

**Comment by LucPrestin** [comment]
I uploaded a Gemfile to the branch skeleton/#1-gem-selection

If you miss one, let me know

**Comment by chrisma** [comment]
Thanks! I’ll have a look! Anything so should pay special attention to?

**Comment by LucPrestin** [comment]
I don't think so. I just want to be sure nothing is missing.

**Comment by LucPrestin** [comment]
In fact: there is something I wanted to ask.

I remember from last year, that you insisted on ruby 2.5.1. 
The ruby version, pacman installs by default is ruby 2.7.1, so I set that as the ruby version. Was there a particular reason to insist on ruby 2.5.1 last year?

**Comment by chrisma** [comment]
> Was there a particular reason to insist on ruby 2.5.1 last year?

Was that possibly the latest stable version last year? The current latest stable version is 2.7.2. I have added that version to the Gemfile. We should also add it to a `.ruby_version` file. **EDIT:** Done. 

Unfortunately, distribution package managers are not always up-to-date. I recommend using [rbenv](https://github.com/rbenv/rbenv-installer#rbenv-installer) as it also allows switching between different ruby versions.

**Comment by chrisma** [comment]
Here is a **default** Gemfile created with Rails 6 using `rails new blog --skip-spring --skip-listen`

```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.7.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.4'
# Use sqlite3 as the database for Active Record
gem 'sqlite3', '~> 1.4'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Use SCSS for stylesheets
gem 'sass-rails', '>= 6'
# Transpile app-like JavaScript. Read more: https://github.com/rails/webpacker
gem 'webpacker', '~> 4.0'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.0'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.4.2', require: false

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
end

group :development do
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'web-console', '>= 3.3.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of web drivers to run system tests with browsers
  gem 'webdrivers'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

**Comment by chrisma** [comment]
I'll try to remove webpack (which is new in Rails 6) and rely on `Sprockets`, the Rails Asset Pipeline, see my comments in #13

**Comment by chrisma** [comment]
We're using Webpacker for this application
