### ISSUE TITLE
Cannot edit user profile

### ISSUE THREAD

**Issue by LinqLover** [hpi-swt2/contacts-portal#108]
If I try to add a last name to my account, for example, the page does not reload. It does not even show an error. Is this maybe related to the way how the date is input?

Broken on dev branch.

**Comment by felixauringer** [comment]
I just tried it locally and everything works fine :thinking:

**Comment by felixauringer** [comment]
> If I try to add a last name to my account, for example, the page does not reload. It does not even show an error. Is this maybe related to the way how the date is input?
> 
> Broken on dev branch.

Hm, I see. On the deployed version I cannot edit my profile too.

**Comment by LinqLover** [comment]
Seems to be fixed again - maybe via #86? Anyway, great! 😃
