### ISSUE TITLE
Add correct I18N metadata

### ISSUE THREAD

**Issue by LinqLover** [hpi-swt2/contacts-portal#123]
Not sure how this should be implemented, but Google Chrome just proposed me to translate this page from Portugisian, which I'm quite you should be able to prevent by providing the right meta tags:

![image](https://user-images.githubusercontent.com/38782922/104763719-9dc2c480-5766-11eb-9c56-5adecddd0daf.png)

**Comment by j-hellenberg** [comment]
We might have considered doing this eventually if we had more time but since that is not the case, we won't care about that for now.
