### ISSUE TITLE
[Process Part] Search For Users

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#127]
# Description
Als Nutzer möchte ich andere Benutzer über eine Suche finden können.

# Dependencies
- [ ] #126

# Conditions of satisfaction
- [ ] im Header gibt es ein Suchsymbol, auf das ich klicken kann und dann werden mir nur noch Benutzerkarten angezeigt, die zu der aktuellen Suche passen

**Comment by florian-papsdorf** [comment]
![Send Contacts Invites](https://user-images.githubusercontent.com/49521681/104849545-86acdf80-58ea-11eb-9069-4f933862c75d.jpg)


zugehöriges Wireframe

**Comment by LinqLover** [comment]
Can you specify how this is different from #23 and #126?

**Comment by florian-papsdorf** [comment]
- Klicke Search-Button
- Redirect zu Search-Page
- Textfeld für Suchbegriff
- erste Ergebnisse sind Kontakte, danach Personen auf der Platform
- es gibt aber Möglichkeit Filter zu setzen, entweder nur nach Kontakte oder nur nach Benutzer zu suchen

**Comment by Paula-Kli** [comment]
#23 is doing that right?

you can find the feature using /users/search

**Comment by LinqLover** [comment]
Analogously to https://github.com/hpi-swt2/connections-portal/issues/126#issuecomment-765599095, this story focuses on a nice and consistent design of the (maybe already existing) feature.
