### ISSUE TITLE
⚙️ Document dependencies in README

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/contacts-portal#13]
The following things are required: https://guides.rubyonrails.org/getting_started.html#creating-a-new-rails-project-installing-rails

![image](https://user-images.githubusercontent.com/1652117/96577471-f56ea280-12d3-11eb-9cc2-6d9f54832e4a.png)

It's true:

Node ![image](https://user-images.githubusercontent.com/1652117/96577360-ce17d580-12d3-11eb-8b1d-2a204b233249.png)

**Comment by chrisma** [comment]
Hmmm... If I'm understanding it correctly, Node.js and Yarn are only required for webpacker, which simply bundles assets (https://webpack.js.org/). This job can also be done via the previous Rails Assets Pipeline, maybe not as nicely?
However, it seems neater to just stick with the Asset Pipeline (with internal, gem dependencies incl. `mini_racer`) than having everyone install node and yarn manually.

**Comment by chrisma** [comment]
Actually, this whole Webpack(er) things seems fairly dumb, imho

> Like Webpack, Sprockets is an asset pipeline, which means it takes assets files as input (Javascript, CSS, images, etc.) and processes them to produce an output in the desired format.
As of Rails 6, Webpack(er) replaces Sprockets as the new standard for writing Javascript in your Rails applications. However, Sprockets is still the default way of adding CSS to your applications.
-- https://blog.capsens.eu/how-to-write-javascript-in-rails-6-webpacker-yarn-and-sprockets-cdf990387463

We should try to stick to the Rails (5) Asset Pipeline using Sprockets for the project, which handles all assets. We don't care if ES6 is maybe not handled well, just don't write that. We're still including jQuery over here... I don't think we necessarily need the power (and complexity) of webpack

**Comment by chrisma** [comment]
Maybe StackOverflow knows more: https://stackoverflow.com/questions/64466331/is-it-possible-advisable-to-run-rails-6-without-webpacker

**Comment by chrisma** [comment]
I've also opened an issue on the rails project: https://github.com/rails/rails/issues/40438

**Comment by chrisma** [comment]
The intro exercise will definitely not use webpacker and will continue to rely on Sprockets and the Rails Asset Pipeline. It doesn't need JS and thus doesn't really care about node.js and yarn dependencies.

It's definitely possible to rely on the Asset Pipeline in Rails 6 projects, I've tried it out here: https://github.com/chrisma/rails6-github-actions/commits/main

After my research I'm unsure about using webpacker for the main project.

Pros:
* It's the Rails 6 default, so many googled answers will include references
* It's modern
* future-proof

Cons:
* Requires (separately) installing node.js and yarn
* Extra complexity

@LucPrestin @rteusner What do you think?

**Comment by swt2public** [comment]
We'll use webpacker for the project

**Comment by chrisma** [comment]
See https://github.com/hpi-swt2/connections-portal#development-setup
