### ISSUE TITLE
See my contacts

### ISSUE THREAD

**Issue by inadicis** [hpi-swt2/contacts-portal#135]
# Description
Als Benutzer möchte eine Liste an meine Kontakte haben, wo ich schnell ihre Stati sehen kann

# Conditions of satisfaction
- [ ] Ich kann die Kontakte-Seite erreichen, indem ich auf ein "Contacts"-Button clicke, der sich im BottomBar befindet
- [ ] Jeder Kontakt hat eine Karte, mit Vorname, Name, Status, Profilbild, und Handles-Icons
- [ ] Die Karten werden nach Vorname alphabetisch sortiert
- [ ] Ich kann die Karten nach Name, Vorname, oder Status filtern
- [ ] Wenn ich auf der Karte clicke, bin ich auf der Profil-Seite des Kontakt geführt (siehe #136)
- [ ] Wenn ich auf den Call-Icon drücke, werde ich durch Jitsi direkt mit die Person in Kontakt gestellt (siehe #137)

# Wireframe

![contacts Wireframe](https://user-images.githubusercontent.com/49560513/105082630-29549200-5a94-11eb-8e1d-cc4c06e4e150.png)

**Comment by florian-papsdorf** [comment]
Kleine Symbole, die den Status repräsentieren, bringen Mehrwert für farbenblinde Menschen & allgemein ist Mapping Mood auf Farbe nicht trivial.

**Comment by inadicis** [comment]
> 
> 
> Kleine Symbole, die den Status repräsentieren, bringen Mehrwert für farbenblinde Menschen & allgemein ist Mapping Mood auf Farbe nicht trivial.

Also lieber nur die Beschreibung des Status? Ich finde farbe praktisch, um schnell eine Übersicht zu bekommen, ohne immer lesen zu müssen, beim scrollen. Ja, farbenblinde Menschen können es nicht sehen, aber deswegen ist es auch daneben geschrieben. Mapping ist nicht trivial, aber man könnte eins setzen.
