### ISSUE TITLE
Contact Card

### ISSUE THREAD

**Issue by inadicis** [hpi-swt2/contacts-portal#143]
# Description
As a user I want to have fo each contact in the contact-page a nice looking card, with first name, last name, profile picture and the handles-icons (buttons) of the contact

# Wireframe
![contact page](https://user-images.githubusercontent.com/49560513/105503512-f80fd800-5cc6-11eb-9889-170262bb1e9e.png)

# Conditions of satisfaction

- [x] Profile Picture 
- [x] First and Last Name
- [x] email adress
- [x] Handle-buttons

**Comment by LinqLover** [comment]
Now I'm really confused about which part of this story is not yet implemented via #117. Search functionality is not a part of this, is it? IIUC this could be closed. @inadicis? :-)
