### ISSUE TITLE
Navigation problems

### ISSUE THREAD

**Issue by frcroth** [hpi-swt2/contacts-portal#160]
Mobile:

- [x] What does the 4th button (the fa-history button) do / what is planned here?
- [x] Proposals and activities should be removed
- [x] Double navbar is a little weird
- [x] Chat and home are selected at the same time
- [x] Chat in the lower navbar does not lead to chat
- Chat is not scrolled down (#178)

Desktop:

- [x] Contacts and requests are not visible
- [x] Proposals and activities should be removed
- [x] There is no way to get to my own page
- [x] There is no way to return to dashboard when on a seperate page
- [x] There is no way to go to contacts

**Comment by LinqLover** [comment]
IMO this should get a high priority, it's a massive regression of our product

**Comment by rheaSPK** [comment]
This isn't a bug, these exact points were explicitly mentioned in the acceptance criterias. I'm not happy with this solution too, so yes, this should be fixed. Maybe we should keep the old navbar for desktop and add the new one only for mobile... But that's up to the POs

**Comment by LinqLover** [comment]
I believe the POs would expect us not to give up our common sense, it's just their responsibility to steer and overview the entire product in great detail ... But however, @florian-papsdorf would be nice to provide an appropriate wireframe to solve this :-)

**Comment by j-hellenberg** [comment]
We currently don't care about the desktop version at all.

Concerning the mobile version, I think the points Felix brought up are what's left to do to reach proper navigation following the wireframes in #138 (+ chat tab).
Refer to #138 as well to see what is planned in the history tab.

**Comment by Alexander-Dubrawski** [comment]
There is still one bug with the navigation bar. If you click on the search icon the link of the settings page is expanding over the whole page. That means that if I click somewhere on the page I get redirected to the edit user page. A quick fix for that is to wrap the link and Icon into a label and then give the label and link the following styling: 

```css
    .nav-bar-entry {
      position: relative;
    }
```

and the link should get the styling:

```css
    a::after {
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        bottom: 0;
        right: 0;
    }
```

so for example the code could look as: 

```erb
...
      <li class="nav-item">
        <!-- please update the path when reworked the chat -->
          <label class="nav-bar-entry">
          <a class="nav-link <%= active_link_to_class(root_path, active: :exclusive)%>" href="<%= root_url %>">
            <i class="fa fa-comments"></i>
          </a>
        </label>
      </li>
...
```

This is just a small trick to style links correctly.

**Comment by Alexander-Dubrawski** [comment]
@rheaSPK is it still possible to log out, or am I missing something? 🙃

**Comment by rheaSPK** [comment]
No, unfortunately it's not. This could be added in the settings page...

**Comment by LinqLover** [comment]
> This could be added in the settings page...

Planned as part of #47.

**Comment by frcroth** [comment]
Removed activities and proposals with #164

**Comment by frcroth** [comment]
#177 fixes this 

> Fixes #160 (apart from non-clickable history, that is described in #166 and scrolling down in the chat that is addressed in #178)

**Comment by LinqLover** [comment]
> - [ ] Chat is not scrolled down

is still unchecked

**Comment by frcroth** [comment]
> 
> 
> > * [ ]  Chat is not scrolled down
> 
> is still unchecked

Yes but its #178 now
