### ISSUE TITLE
Interaction suggestions depending on own status

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#165]
## User Story

**As a** user -  
**I want to** only receive suggestions for users I might call on the dashboard tab if I have set the status "Available" or "Nice2MeetU" -  
**In order to** avoid distractions when I'm busy. 

## Conditions of satisfaction

- [x] if I have not set an appropriate status, I don't get any suggestions (see wireframe)
- [ ] if I have set an appropriate status, I receive up to 4 suggestions **of users which have set a status of available or Nice2MeetU** with one of them standing out (see wireframe)

## Implementation Note

Don't care too much about card design here, this is subject of another issue.

## Wireframe

![image](https://user-images.githubusercontent.com/47941549/106451908-7880c680-6487-11eb-83d8-0148b5b8d3c6.png)

**Comment by frcroth** [comment]
What I need from the PO's is a clear message what every status means:  
What is free for chat and why does it exist?  
What should the offline mode do?  
Are there differences between available and nice to meet you?

**Comment by frcroth** [comment]
Free for chat may be deleted (needs a migration)
