### ISSUE TITLE
Chat should show user avatars

### ISSUE THREAD

**Issue by frcroth** [hpi-swt2/contacts-portal#179]
As I understand it, you can access the user avatar via user.avatar. This would make it possible for the chat to show the user avatar instead of a placeholder. For dynamic messages this is harder, a path like users/id/avatar would be nice if it doesn't exist yet.

- [x] Chat that is rendered on reload shows avatars
- [x] Chat that is generated via web socket shows avatars

By the way, the user list on the dashboard should show avatars as well

**Comment by chrisma** [comment]
Related to #185?
