### ISSUE TITLE
Profile Picture does not survive

### ISSUE THREAD

**Issue by inadicis** [hpi-swt2/contacts-portal#182]

**Comment by inadicis** [comment]
Bug is not reproduicable

**Comment by chrisma** [comment]
See also https://devcenter.heroku.com/articles/active-storage-on-heroku (/cc @Paula-Kli )

**Comment by chrisma** [comment]
First step to debug could be to run the dev server in `production` mode (`RAILS_ENV=production bin/rails server`) to see if the problem is reproducible locally

**Comment by Paula-Kli** [comment]
there are several ideas how to cope with the ephemeral filesystem of heroku:
- save the image in an external service
- save the minimized and serialized image in the db
- allow users to only upload images from external urls
- use [gravatar]( https://github.com/chrislloyd/gravtastic)
Thanks to @chrisma

**Comment by frcroth** [comment]
I don't know what the PO's say but as a user I would be fine with giving a link to an image or linking gravatar

**Comment by felixauringer** [comment]
>     * use [gravatar](https://github.com/chrislloyd/gravtastic)
>       Thanks to @chrisma

Looks like this isn't maintained anymore :sweat_smile:

**Comment by felixauringer** [comment]
For anyone else who wonders what the problem is: Heroku explaines it on [this page](https://devcenter.heroku.com/articles/active-storage-on-heroku)

**Comment by inadicis** [comment]
I would find it weird, as a user, that I have to look for a image-hosting service first, in order to set my profile picture. I would rather upload it directly into our website. 
Therefore I would tend for one of the alternatives, I guess saving in the database is the easiest way.

**Comment by felixauringer** [comment]
Another option would be to install (if that is possible) a local storage server like [minio](https://github.com/minio/minio) on Heroku. Its API ist Amazon S3 compatible and should be usable with rails.
EDIT: After rethinking this, I assume Heroku would clear the data of a local minio, too.

**Comment by frcroth** [comment]
I think if we want to fix this, only external links are realistic given the timeframe

**Comment by felixauringer** [comment]
> I think if we want to fix this, only external links are realistic given the timeframe

I would contradict, see #195 :P
