### ISSUE TITLE
Add Button to Header which allows to logout

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#186]

**Comment by chrisma** [comment]
Have you considered the differences to the implementation currently deployed on dev?

![image](https://user-images.githubusercontent.com/1652117/107044021-0cbe9680-67c4-11eb-8cc1-bb5bba8a8731.png)

**Comment by felixauringer** [comment]
> Have you considered the differences to the implementation currently deployed on dev?

This button is currently only available in the desktop view, this ticket is for adding it to the mobile view.
