### ISSUE TITLE
🏗️ Setup automated Heroku deploy

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/contacts-portal#2]
As teams will be remote much of the time, a deployed version of the application that is automatically updated seems even more important than previously and should be available from the start of the course.

I suggest using [Heroku](https://www.heroku.com/) again, as it has worked well for RoR apps in the past (but I'm also open to alternatives). There's no reason not to have deployments on multiple providers.

- [x] Automated deploy of **dev** branch, after successful tests, to Heroku (using [GitHub Actions](https://github.com/marketplace/actions/deploy-to-heroku))
- [x] Automated deploy of **main** branch, after successful tests, to Heroku (using [GitHub Actions](https://github.com/marketplace/actions/deploy-to-heroku))
- [x] Add Heroku badges to README
- [x] Add links to deployments to README
- [x] Add information on how to find detailed information on last test / deployment run in README

**Comment by LucPrestin** [comment]
- [x] Add the app on Heroku
- [x] Add Heroku token to the github secrets
- [x] Add app name and secret token to the workflow file

**Comment by LucPrestin** [comment]
Does the chair have a Heroku-Account that we can use for the deployment or do I have to create one?

**Comment by chrisma** [comment]
> Does the chair have a Heroku-Account that we can use for the deployment or do I have to create one?

You have mail :)

**Comment by LucPrestin** [comment]
What are Heroku-Badges? I could not find any information on that.

**Comment by chrisma** [comment]
> What are Heroku-Badges? I could not find any information on that.

Apologies, that is bad wording on my part... I meant these (in the README):
![image](https://user-images.githubusercontent.com/1652117/96734938-52915380-13bb-11eb-9a68-882ca511bf0a.png)

**Comment by LucPrestin** [comment]
> > What are Heroku-Badges? I could not find any information on that.
> 
> Apologies, that is bad wording on my part... I meant these (in the README):
> ![image](https://user-images.githubusercontent.com/1652117/96734938-52915380-13bb-11eb-9a68-882ca511bf0a.png)

I see. I will add them.

**Comment by LucPrestin** [comment]
I added both badges, but the build badge will only work when the workflow file gets to the master branch, as GitHub only generates the workflow when it is.

**Comment by chrisma** [comment]
> I added both badges, but the build badge will only work when the workflow file gets to the master branch

Let's do it (and merge the preparation branch into main to test this out)!

**Comment by LucPrestin** [comment]
We should probably wait until the [PR about the skeleton code](https://github.com/hpi-swt2/rolodex-portal/pull/16) is merged. Otherwise, the GitHub Action won't have anything to test. If we wait until then, we can test whether it deploys correctly at the same time.

**Comment by chrisma** [comment]
Done: https://github.com/hpi-swt2/connections-portal/blob/dev/.github/workflows/CI_CD.yml
