### ISSUE TITLE
Discord-Logo is not shown

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#213]
![image](https://user-images.githubusercontent.com/47941549/107436491-e5522b80-6b2d-11eb-9f9d-0dd73a9d0a56.png)

**Comment by frcroth** [comment]
This is because discord is a font awesome 5.0 addition. I attempted to include this with https://github.com/tomkra/font_awesome5_rails but didn't get it to work right now.

**Comment by frcroth** [comment]
The discord icon is not available in Versions 4 or earlier of Font Awesome. I tried to include it through https://github.com/tomkra/font_awesome5_rails but this did not work immediately.
