### ISSUE TITLE
View list of all accounts

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#22]
As a User, I'd like to see a list of all accounts at the home screen, in order to have an overview of all people using the platform.

## ✅ Conditions of satisfaction

- [x] Should be visible in the Home-Screen
- [x] Should show a table, with one row per account
- [x] In a row should be shown the email address of the account
- [x] Should show all existing accounts

**Comment by Paula-Kli** [comment]
As a User I want to see a list of all accounts at the home screen to have an overview of all people using the platform.

**Comment by Paula-Kli** [comment]
Done: you can see all users

**Comment by antoniusnaumann** [comment]
3 Std. Teamzeit

**Comment by SanJSp** [comment]
2h 30min til PR
