### ISSUE TITLE
Search users by email adress, first name or last name

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#23]
# Description
As a user, i want to be able to search for other users, using their first, last name or email address

# Hints & Thoughts
* is not dependant to #72 , but both work with mails, devs maybe want to have the same team doing both or choose a convention

# Conditions of satisfaction
- [ ] there is a ui-design wireframe, how it should look like
- [x] There is a new page, reserved to searching for users
- [x] in this page, there is a search-field and a list of users
- [x] if i enter a string in the search-field, the list of users is filtered after my entry (looks for substrings-matching)
- [ ] fix tests

# Extensions
- [ ] I can change the sorting-method of the list
- [ ] i can change how much users the table shows
- [ ] i can navigate between results-pages

**Comment by Paula-Kli** [comment]
done: search for string if this is equal and afterwards also search for substrings

**Comment by PatriciaSowa** [comment]
Die selbstgeschriebenen Tests laufen noch nicht vollständig durch.
