### ISSUE TITLE
Add other account as contact

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#25]
As a User, I'd like to add another user as one of my contacts from the global account list.

---
### 🔙 Dependencies
Other Issues that need to be closed before:
- #22 

### 💭 Hints & Thoughts
The list of accounts does not need to be displayed (see #26)

---

## ✅ Conditions of satisfaction

- [x] In the row of the global account list, there should be a "+" button on the right side
- [x] In the data bank, for each account, there should be a list of all its contacts
- [x] The "+" button should add the account from the same row to the contacts list of the registered user

**Comment by Paula-Kli** [comment]
done: through the contact list (#22 ) you can add another account using a '+' and a user has a list of all added accounts (does not need to be displayed => #26 )

**Comment by antoniusnaumann** [comment]
4 Std. Teamzeit
