### ISSUE TITLE
Show accounts in contact list

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#26]
As a User, I'd like to see a list of my contacts in a new page, accessible from the home page, in order to see who I have as contact

### 🔙 Dependencies
Other Issues that need to be closed before:
- #25
---

## ✅ Conditions of satisfaction

- [x] Should be visible in a "Contacts" page
- [x] The Contacts page should be accessible by clicking on a button in the scaffold
- [x] In the Contacts page there should be a table with one row per account that I have in my contact list
- [x] In a row should be shown the email address of the account

**Comment by antoniusnaumann** [comment]
Done: Tab with "contact list", display a list of saved contacts

**Comment by antoniusnaumann** [comment]
5 Std. Teamzeit

**Comment by SanJSp** [comment]
This issue was implemented with #53 but had a failing test. The failing tests were fixed after a hotfix commit on dev https://github.com/hpi-swt2/connections-portal/commit/ffa1115cfc6b26259821e7fec3b602630a082bdc
