### ISSUE TITLE
Filter by current status

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#31]
## User Story

**As a** user -  
**I want to** filter accounts by their current status -  
**In order to** communicate with users that might currently be willing to do so.

## References
- #68 (non-blocking)

## Conditions of satisfaction
- [x] a list of users who have the status `free for chat` set is displayed
  - [x] it should include 30 entries if available (scroll on overflow)
  - [x] at least first name and last name (username as fallback) and a placeholder for a profile-picture is displayed 
  - [x] the list should be in randomised order

## Implementation Note

Please discuss with the PO if you can think of any more information that might make sense to be included in the account list.

**Comment by Paula-Kli** [comment]
done: search for string if this is equal and afterwards also search for substrings
