### ISSUE TITLE
Categorize contacts

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#35]
- e.g. by friends, colleagues
- static for now, custom categories might be added later
- list is filterable

**Comment by LinqLover** [comment]
Depends on #33.

**Comment by LinqLover** [comment]
Current state: We were not sure whether it is okay to limit the number of notes per describing user and described user to 1 (see #33). @hpi-swt2/product-owner feedback needed for this. /cc @rheaSPK 
If this limitation is not acceptable, this feature will need to use another association class for contacts anyway and it does no longer depend on #33.

**Comment by LinqLover** [comment]
@hpi-swt2/product-owner Did I choose the right label for this purpose? :)

**Comment by LinqLover** [comment]
Wait, is this related to/based on #25 (which I just discovered by chance only)? @florian-papsdorf Please clarify!
