### ISSUE TITLE
Option to start jitsi meeting

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#42]
## User Story

**As a** user -  
**I want to** be able to start a jitsi meeting -  
**In order to** speak with other people on the platform.

## Conditions of satisfaction

- [x] a new random jitsi meeting id can be automatically generated
- [x] the meeting id should be assigned to two users:
  - [x] user who initiated creation
  - [x] user the meeting should be initialized with
- [x] when clicking a certain button associated with another user, setup meeting id with that user

## Implementation Note

Hard-code the url from a server where meetings can be hosted on.

**Comment by frcroth** [comment]
Storypoints: 3

**Comment by felixauringer** [comment]
As we only have 3 story points left for the sprint starting on 2021-01-08, it is not required to finish this issue.
