### ISSUE TITLE
Team 3 Environment Setup

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#43]
Every team member has a running development environment on his computer.

**Comment by LinqLover** [comment]
Setup working for:

- [x] @florian-papsdorf 
- [x] @Alexander-Dubrawski
- [x] @LinqLover
- [x] @rheaSPK

**Comment by LinqLover** [comment]
@florian-papsdorf Does the setup work for you or do you not intend to get it running? If yes, this issue could be closed.

**Comment by florian-papsdorf** [comment]
@LinqLover Thank you for your notice! The environment is running now, so I can check status and review features.

**Comment by LinqLover** [comment]
(Alright, now the automation works :-)

![image](https://user-images.githubusercontent.com/38782922/101246458-c55c5100-3713-11eb-8953-6e8d0c7d40cf.png))
