### ISSUE TITLE
Settings Page Zoom ID

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#48]
As a User I want to edit my Zoom credentials on the settings page.

Depends on #47.

**Comment by LinqLover** [comment]
We could easily support this via #69 if we added "Zoom" to the list of allowed platforms (this would be a diff of 1 lines in source code). Interested?

**Comment by j-hellenberg** [comment]
Together with the customer, we decided to not support zoom as a call platform, because we did not like that the user would have to share his personal zoom meeting with the platform (#36). Therefore, we don't need to include a handle for zoom.
