### ISSUE TITLE
Delete Account

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#49]
As a User I want to have the ability to delete my account on Contacts++ with the help of a button on the settings page (see #47).

**Comment by LinqLover** [comment]
How does the remittal of this issue fit together with our non-functional compliance requirements (GDPR and your right to be forgotten)? Just asking :)

**Comment by j-hellenberg** [comment]
There is no need for that, if you don't use the platform because it does not provide you any value ;)
For this reason, we will focus on providing functionality first and will come back to some of the remitted issues if there is time left afterwards
