### ISSUE TITLE
Link to GitHub page

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#64]
# Description
As a software engineering enthusiast I want to save a link to the GitHub page of the contact.

# Conditions of satisfaction
- [ ] each contact can store a link to a GitHub Profile/Page
- [ ] If I click the link, I will be redirected to the GitHub Page

**Comment by LinqLover** [comment]
@florian-papsdorf Please, add a reference to the other issue when you mark an issue as a duplicate. It is so hard to find out what you are referring to without this information ... :-)
