### ISSUE TITLE
[ ] Wireframe

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#65]
<img width="875" alt="Bildschirmfoto 2020-12-07 um 18 48 08" src="https://user-images.githubusercontent.com/49521681/101385951-c41a5800-38bc-11eb-9d4c-4514406e04e6.png">

**Comment by LinqLover** [comment]
In which way is this assigned to team 3? It rather looks as if chat would be an epic handled by team 1 (see #77 and others). However, the draft looks very nice! :-)
