### ISSUE TITLE
[User Story] Import Telegram Contacts

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#67]
# Description
As a user I want to import all my Telegram contacts into the platform because the major part of communication is on Telegram.

# Conditions of satisfaction
- [ ] first, last name and the telegram handle is imported

**Comment by LinqLover** [comment]
Are we only talking about contacts? Not sure to how many users this applies, but personally, I'm not actually using my contact directory in Telegram. Just scanning the entire chat list for all persons that have been contacted frequently might be a more fecund approach?

EDIT: Might be considered.
