### ISSUE TITLE
[User Story] Profile Picture

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#68]
## User Story
**As a** user -
**I want to** add a profile picture to my account -
**So that** it is easier for other users to know who I am.

## Conditions of satisfaction
- [ ] I can upload a picture
- [ ] the picture is shown on the settings page
- [ ] if there isn't any picture uploaded, a default picture will be there

**Comment by LinqLover** [comment]
to be reevaluated
