### ISSUE TITLE
[User Story] Store User Handles

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#69]
# Description
As a user I want to store various handles to each contact.

# Conditions of satisfaction
- [ ] I can store Telegram, Facebook, Twitter, GitHub, GitLab@HPI, Slack Discord handles
- [ ] Even if possible, the handle will redirect to a corresponding page
- [ ] the redirect will open a new tab

**Comment by LinqLover** [comment]
Do we indeed want to hard-code the list of account platforms? I could imagine that an arbitrary mapping where could enter custom platform names as keys would be more flexible and extendable. (Maybe out of scope, but we could still encourage the user to enter their handles for well-known platforms by suggesting platform names that have been commonly indicated on the platform. Or only hard-code these suggestions.)

**Comment by LinqLover** [comment]
> Do we indeed want to hard-code the list of account platforms? I could imagine that an arbitrary mapping where could enter custom platform names as keys would be more flexible and extendable. (Maybe out of scope, but we could still encourage the user to enter their handles for well-known platforms by suggesting platform names that have been commonly indicated on the platform. Or only hard-code these suggestions.)

We decided to defer this if done at all. TODO: Create another issue.

**Comment by florian-papsdorf** [comment]
@Alexander-Dubrawski 
We store the handles for each contact in our address book. Of course an option to store our own handles on our own profile page might be helpful.
The next step (not in scope of this issue) would be a matching between our address book and the global contacts++ address book.
