### ISSUE TITLE
📊 Add diagram of data model

### ISSUE THREAD

**Issue by chrisma** [hpi-swt2/contacts-portal#7]
- [ ] Document the current state of the data model in a (ER) diagram
- [ ] Investigate auto-generating this thing. Can it be produced via GitHub Action and added to README?

**Comment by LucPrestin** [comment]
A UML-diagram can be manually generated with RubyMine.

Even though it is not as automated as a GitHub Action, it may be interesting in case, we have problems doing this with a GitHub Action.

https://www.jetbrains.com/help/ruby/creating-diagrams.html

**Comment by chrisma** [comment]
That info should go into the README!

**Comment by LucPrestin** [comment]
It will. I just wanted to write it down quickly in order to not forget it.

**Comment by chrisma** [comment]
It's in the README, thanks
