### ISSUE TITLE
[ Brain Storming ] Additional status

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#70]
Besides available and offline, which status we need, too? Should be around 10 hardcoded values in total.

**Comment by LinqLover** [comment]
Would it be a good or bad idea to allow a short free text as the status?

**Comment by LinqLover** [comment]
Brainstorming:
- 🟢 Available
- 🚫 Offline
- 🤓 Coding
- 👂 Lecture
- 💬 Meeting
- 🍽 Eating
- 💤 Sleeping

**Comment by florian-papsdorf** [comment]
* Nice 2 Meet U
* Drinking Coffee
* In hurry
* Busy

**Comment by LinqLover** [comment]
> - In hurry

From a practical point of view, when will I ever be in a hurry but still have the time to set my status to in hurry? :-)

**Comment by rheaSPK** [comment]
- Lonely
- Need mental support
- casual chitchat wanted
- friends only
- want to meet new people

**Comment by LinqLover** [comment]
Do we want to label each state with a Unicode icon?

**Comment by LinqLover** [comment]
@florian-papsdorf There are some proposals now. I think it's up to you as the PO to make a final decision, or to delegate the decision to someone else? :)

**Comment by florian-papsdorf** [comment]
The proposals sounds very well and I will talk about them with the customer next time.
