### ISSUE TITLE
Team name

### ISSUE THREAD

**Issue by inadicis** [hpi-swt2/contacts-portal#74]
# Description
As a product owner i want my team to have an explicit name, to avoid handling to much with numbers

# Conditions of satisfaction
- [x] the team should choose a name
- [x] the name shall not be just numbers or random characters
- [x] "team of Nils Cichy" or similarly define the team by its PO is not allowed
- [x] the name should be humorous :)

**Comment by LinqLover** [comment]
Funny, team 2 is https://github.com/hpi-swt2/connections-portal/projects/3 and team 3 is https://github.com/hpi-swt2/connections-portal/projects/2 😂

**Comment by LinqLover** [comment]
Team 2 is now Team ε.

**Comment by frcroth** [comment]
Team 1 is "Codemoon und Felix"
