### ISSUE TITLE
Dropdown for setting own status

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#76]
## User Story

**As a** user -  
**I want to** have a dropdown on the dashboard page for setting my status -  
**In order to** be able to quickly update it.

## Dependencies
- [x] requires #28 

## Conditions of satisfaction
- [x] the dropdown exists
- [x] selecting a entry changes my status
- [x] a status named `free for chat`

**Comment by frcroth** [comment]
Closed with #94
