### ISSUE TITLE
Global chat

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#77]
## User Story

**As a** user -  
**I want to** have a global live-chat -  
**In order to** engage with the other users that are currently active on the site.

## Dependencies
- [x] builds partially on #31 

## Conditions of satisfaction
- [x] messages can be sent
- [x] messages of other users are received in real-time

## Implementation Note

Building a custom chat here is not a requirement.

Maybe have a look at <https://iridakos.com/programming/2019/04/04/creating-chat-application-rails-websockets>

Note: Maybe later one channel per status

**Comment by mpass99** [comment]
We want to build a live chat and we already have the frontend graphics.
There are two main solutions:
- https://github.com/chaskiq/chaskiq
Is a full-featured live-chat with an own rails backend and a embeddable react.js client with video call integration.
- https://iridakos.com/programming/2019/04/04/creating-chat-application-rails-websockets
A guide how to create a simple live chat for rails via a websocket connection

On the one hand the chaskiq, it's integration effort and the effort to integrate custom features in future might be too big.
On the other hand we don't need to reinvent all the common features

**Comment by mpass99** [comment]
Our PO has decided against chaskiq
