### ISSUE TITLE
Contribute to feed

### ISSUE THREAD

**Issue by j-hellenberg** [hpi-swt2/contacts-portal#79]
## User Story

**As a** user -  
**I want to** contribute short texts to the activity feed of my contacts -  
**In order to** let others know what I am currently doing/thinking about and provide a possible starting point for a conversation.

## Conditions of satisfaction
- [ ] an option to persist my texts exists
- [ ] it should be added to my personal feed

**Comment by frcroth** [comment]
Closed with #103
