### ISSUE TITLE
Do not show navbar links to user-specific pages before logging in

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#95]
Links to notes, My contacts and Home should only viewed after Login.

**Comment by LinqLover** [comment]
@florian-papsdorf Please clarify.

Are you talking about this "dead link" when logged off? The other links work well.

![image](https://user-images.githubusercontent.com/38782922/103876348-d19d4a80-50d3-11eb-92da-0fd5dac0b613.png)

Or is it your acceptance criterion to hide all buttons except the home button from the navbar when the user is logged off?
Or do you also want to ban users from accessing these URLs manually?

**Comment by florian-papsdorf** [comment]
![image](https://user-images.githubusercontent.com/49521681/103905488-f65ae780-50fe-11eb-9014-e45e79c7a10b.png)

There are buttons before I'm logged in, like My Contacts.

**Comment by LinqLover** [comment]
Recap:

> Or do you also want to ban users from accessing these URLs manually?

Yes. Compliance matters.

**Comment by LinqLover** [comment]
@florian-papsdorf At the moment, when not logged in you are redirected to the log-in page if you try to manually access a protected URL such as the user list. Is it important for you that one is automatically redirected back to the protected URL after authenticating properly?

**Comment by rheaSPK** [comment]
Since the navbar is reworked by me and this behaviour doesn't occur in the mobile version at least, I'm wondering if this ticket really needs to be worked on.

**Comment by LinqLover** [comment]
@rheaSPK This issue was not only about the UI (this was the easiest part) but also about the controller logic because we wanted to ban every unauthenticated user to from all user pages, even if they enter a URL manually. I have just merged this! :-)
