### ISSUE TITLE
[User Story] Search For Contacts In Mobile Version

### ISSUE THREAD

**Issue by florian-papsdorf** [hpi-swt2/contacts-portal#98]
# Description
As a user I want to search for contacts on my mobile, too.

# Dependencies
- [x] #97 

# Conditions of satisfaction
- [ ] the design follows the wireframe below
- [ ] there is a field to search for contacts
- [ ] only related contacts (= search results) are shown
- [ ] search results are alphabetically sorted

![Mobile Contacts v2](https://user-images.githubusercontent.com/49521681/103785684-cbf42600-503b-11eb-9711-2bde7025cf56.png)

**Comment by LinqLover** [comment]
Assumptions (@florian-papsdorf please give feedback):

- search term should only be compared to the name, and there is no fuzzy search requested, just substring search

Implementational steps:
- [ ] write simple acceptance test
- [ ] write controller test
- [ ] adjust controller to have filter parameter
- [ ] adjust view to have search form that redirects to filtered parameter

Possible pitfalls:
- <I can't imagine any ATM (but there will for sure be any)>

**Comment by florian-papsdorf** [comment]
Yes, search team should only compared to the name.

**Comment by LinqLover** [comment]
Belongs to #127.
