### ISSUE TITLE
Navbar is not rendered correctly when screen is narrower than 768px

### ISSUE THREAD

**Issue by LinqLover** [hpi-swt2/contacts-portal#99]
Most likely, the `navbar-collapse` in HTML stuff has not been configured properly ... It should be quite easy to add a hamburger-like menu automatically if the screen is too narrow for expanding all contents. At the moment, the page cannot be handled properly on small screens or on mobile.

**Comment by j-hellenberg** [comment]
This is not an urgent bug right now as in the mobile view we will have the navigation in the footer instead of using the navbar at the top too much.

**Comment by LinqLover** [comment]
I believe this been fixed via #132 by @rheaSPK anyway? :)

**Comment by j-hellenberg** [comment]
Ah, you're right. Unfortunately, we won't be using that in the current state of planning but it's nice to have it working just in case 👍
